/**
 * English canonical country name → Turkish display name.
 * Keys must match what the server's geocoder writes to companies.country
 * (which mirrors COUNTRY_NAMES in countryNames.ts).
 *
 * Used to localize the "Konum" filter dropdown so Turkish users can search
 * by typing "Türkiye" instead of "Turkey". Backend filtering still uses the
 * canonical English form, so we ship label=Turkish, value=English.
 */
export const COUNTRY_NAMES_TR: Record<string, string> = {
    'Afghanistan': 'Afganistan',
    'Albania': 'Arnavutluk',
    'Algeria': 'Cezayir',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Argentina': 'Arjantin',
    'Armenia': 'Ermenistan',
    'Australia': 'Avustralya',
    'Austria': 'Avusturya',
    'Azerbaijan': 'Azerbaycan',
    'Bahamas': 'Bahamalar',
    'Bahrain': 'Bahreyn',
    'Bangladesh': 'Bangladeş',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Belgium': 'Belçika',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Butan',
    'Bolivia': 'Bolivya',
    'Bosnia and Herzegovina': 'Bosna Hersek',
    'Botswana': 'Botsvana',
    'Brazil': 'Brezilya',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgaristan',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cambodia': 'Kamboçya',
    'Cameroon': 'Kamerun',
    'Canada': 'Kanada',
    'Cape Verde': 'Cabo Verde',
    'Central African Republic': 'Orta Afrika Cumhuriyeti',
    'Chad': 'Çad',
    'Chile': 'Şili',
    'China': 'Çin',
    'Colombia': 'Kolombiya',
    'Comoros': 'Komorlar',
    'Costa Rica': 'Kosta Rika',
    'Croatia': 'Hırvatistan',
    'Cuba': 'Küba',
    'Cyprus': 'Kıbrıs',
    'Czechia': 'Çekya',
    'DR Congo': 'Demokratik Kongo Cumhuriyeti',
    'Denmark': 'Danimarka',
    'Djibouti': 'Cibuti',
    'Dominica': 'Dominika',
    'Dominican Republic': 'Dominik Cumhuriyeti',
    'Ecuador': 'Ekvador',
    'Egypt': 'Mısır',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Ekvator Ginesi',
    'Eritrea': 'Eritre',
    'Estonia': 'Estonya',
    'Eswatini': 'Esvatini',
    'Ethiopia': 'Etiyopya',
    'Fiji': 'Fiji',
    'Finland': 'Finlandiya',
    'France': 'Fransa',
    'Gabon': 'Gabon',
    'Gambia': 'Gambiya',
    'Georgia': 'Gürcistan',
    'Germany': 'Almanya',
    'Ghana': 'Gana',
    'Greece': 'Yunanistan',
    'Grenada': 'Grenada',
    'Guatemala': 'Guatemala',
    'Guinea': 'Gine',
    'Guinea-Bissau': 'Gine-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hong Kong': 'Hong Kong',
    'Hungary': 'Macaristan',
    'Iceland': 'İzlanda',
    'India': 'Hindistan',
    'Indonesia': 'Endonezya',
    'Iran': 'İran',
    'Iraq': 'Irak',
    'Ireland': 'İrlanda',
    'Israel': 'İsrail',
    'Italy': 'İtalya',
    'Ivory Coast': 'Fildişi Sahili',
    'Jamaica': 'Jamaika',
    'Japan': 'Japonya',
    'Jordan': 'Ürdün',
    'Kazakhstan': 'Kazakistan',
    'Kenya': 'Kenya',
    'Kosovo': 'Kosova',
    'Kuwait': 'Kuveyt',
    'Kyrgyzstan': 'Kırgızistan',
    'Laos': 'Laos',
    'Latvia': 'Letonya',
    'Lebanon': 'Lübnan',
    'Lesotho': 'Lesoto',
    'Liberia': 'Liberya',
    'Libya': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Litvanya',
    'Luxembourg': 'Lüksemburg',
    'Macao': 'Makao',
    'Madagascar': 'Madagaskar',
    'Malawi': 'Malavi',
    'Malaysia': 'Malezya',
    'Maldives': 'Maldivler',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Mauritania': 'Moritanya',
    'Mauritius': 'Mauritius',
    'Mexico': 'Meksika',
    'Moldova': 'Moldova',
    'Monaco': 'Monako',
    'Mongolia': 'Moğolistan',
    'Montenegro': 'Karadağ',
    'Morocco': 'Fas',
    'Mozambique': 'Mozambik',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibya',
    'Nepal': 'Nepal',
    'Netherlands': 'Hollanda',
    'New Zealand': 'Yeni Zelanda',
    'Nicaragua': 'Nikaragua',
    'Niger': 'Nijer',
    'Nigeria': 'Nijerya',
    'North Korea': 'Kuzey Kore',
    'North Macedonia': 'Kuzey Makedonya',
    'Norway': 'Norveç',
    'Oman': 'Umman',
    'Pakistan': 'Pakistan',
    'Palestine': 'Filistin',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papua Yeni Gine',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Filipinler',
    'Poland': 'Polonya',
    'Portugal': 'Portekiz',
    'Puerto Rico': 'Porto Riko',
    'Qatar': 'Katar',
    'Republic of the Congo': 'Kongo Cumhuriyeti',
    'Romania': 'Romanya',
    'Russia': 'Rusya',
    'Rwanda': 'Ruanda',
    'Saudi Arabia': 'Suudi Arabistan',
    'Senegal': 'Senegal',
    'Serbia': 'Sırbistan',
    'Seychelles': 'Seyşeller',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapur',
    'Slovakia': 'Slovakya',
    'Slovenia': 'Slovenya',
    'Somalia': 'Somali',
    'South Africa': 'Güney Afrika',
    'South Korea': 'Güney Kore',
    'South Sudan': 'Güney Sudan',
    'Spain': 'İspanya',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudan',
    'Suriname': 'Surinam',
    'Sweden': 'İsveç',
    'Switzerland': 'İsviçre',
    'Syria': 'Suriye',
    'Taiwan': 'Tayvan',
    'Tajikistan': 'Tacikistan',
    'Tanzania': 'Tanzanya',
    'Thailand': 'Tayland',
    'Timor-Leste': 'Doğu Timor',
    'Togo': 'Togo',
    'Trinidad and Tobago': 'Trinidad ve Tobago',
    'Tunisia': 'Tunus',
    'Turkey': 'Türkiye',
    'Turkmenistan': 'Türkmenistan',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukrayna',
    'United Arab Emirates': 'Birleşik Arap Emirlikleri',
    'United Kingdom': 'Birleşik Krallık',
    'United States': 'Amerika Birleşik Devletleri',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Özbekistan',
    'Vanuatu': 'Vanuatu',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnam',
    'Yemen': 'Yemen',
    'Zambia': 'Zambiya',
    'Zimbabwe': 'Zimbabve',
};

/**
 * Returns the localized display name for a canonical (English) country name.
 * Falls back to the canonical form when no translation exists.
 */
export function localizeCountry(canonical: string, lang: string): string {
    if (lang === 'tr') return COUNTRY_NAMES_TR[canonical] ?? canonical;
    return canonical;
}
