/**
 * ICP Master (B5) — the structured output contract for ICP generation.
 *
 * The strategy model (Opus, via runLlmJson('strategy', …)) returns a set of ICP
 * drafts shaped like this. The worker freezes the raw object in research_icps.ai_draft
 * (eval data) and projects the fields onto the editable columns the customer then
 * scores /10 and refines. Mirrors the research_icps columns from migration 056.
 */
import { z } from 'zod/v4';

// Bounds mirror the PATCH limits in routes/research/icps.ts. The provider strips
// min/max from the JSON schema sent to the model, but runLlmJson RE-VALIDATES the
// output against this zod schema — so these caps reject (and retry) runaway model
// output before it is persisted to research_icps. Keep them in sync with the route.
const item = z.string().min(1).max(500);
const list = z.array(item).max(100);

/** One ICP segment as generated by the model. Field names mirror research_icps. */
export const icpDraftSchema = z.object({
    /** Human-facing segment name, e.g. "German industrial-valve importers". */
    name: z.string().min(1).max(200),
    /** Short stable code, UPPER-KEBAB, e.g. "IMP-VALVE-DE". */
    code: z.string().min(1).max(64),
    /** One-line description of the segment. */
    segment: z.string().min(1).max(2000),
    /** Positive signals — a firm fits the ICP if these hold (site/role/trade cues). */
    signals: z.array(item).min(1).max(100),
    /** Disqualifiers — presence pushes toward ELIMINATED. */
    negative_signals: list,
    /** Present-but-not-decisive signals (context, not scoring). */
    neutral_signals: list,
    /** Hard elimination rules (if true → ELIMINATED regardless of score). */
    elimination_rules: list,
    /** Illustrative real example firms (lookalikes) — names/domains, for calibration. */
    lookalike_companies: list,
    /** Why this ICP fits the customer profile — shown to the user; stored in ai_draft. */
    rationale: z.string().min(1).max(4000),
});

/** The full generation result: one or more ICP segments. */
export const icpGenerationSchema = z.object({
    icps: z.array(icpDraftSchema).min(1).max(8),
});

export type IcpDraft = z.infer<typeof icpDraftSchema>;
export type IcpGeneration = z.infer<typeof icpGenerationSchema>;
