/**
 * Sub-ICP cell (WP2) — the structured output contract for geo:analyze.
 *
 * The strategy model returns the ICP instantiated for ONE country: local-language
 * search terms, localized signal adaptations, the country's key channels (WP3 seed),
 * certifications, buyer titles (persona seed), market-structure notes and an E
 * estimate. The worker persists the whole validated object into
 * research_geographies.spec (editable final) + ai_draft (frozen model output) via
 * the fenced RPC from migration 086.
 */
import { z } from 'zod/v4';

// Bounds mirror the PATCH limits in routes/research/geographies.ts. The provider strips
// min/max from the JSON schema sent to the model, but runLlmJson RE-VALIDATES the
// output against this zod schema — so these caps reject (and retry) runaway model
// output before it is persisted to research_geographies. Keep them in sync with the route.

const CHANNEL_TYPES = ['association', 'fair', 'directory', 'chamber', 'registry', 'cluster', 'marketplace'] as const;

// Spec strings end up in the VALIDATION prompt's trusted zone (validate.ts renders localized
// cues next to the ruleset) and derive from web evidence — refuse fence-marker lookalikes at
// the schema boundary so a poisoned draft fails validation before it can ever be persisted.
const noFence = (max: number) =>
    z.string().min(1).max(max).refine((s) => !s.includes('<<<'), { message: 'fence markers not allowed' });

/** A named source; url only when the model is confident it is real (never invented). */
const namedSource = z.object({
    name: noFence(200),
    url: z.string().min(1).max(500).optional(),
});

/** One country-level buying channel (association, fair, directory, …) — WP3 discovery seed. */
export const geoChannelSchema = namedSource.extend({
    type: z.enum(CHANNEL_TYPES),
});

/** The full geo-instantiated ICP spec as generated by the model (research_geographies.spec). */
export const geoAnalysisSchema = z.object({
    /** ACTUAL local-language sector/role search phrases a native buyer/directory would use. */
    local_terms: z.array(noFence(120)).min(1).max(12),
    /** Positive cues in the local language — the ICP's signals adapted to local vocabulary. */
    localized_signals: z.array(noFence(500)).max(20),
    /** Local-language disqualifiers — presence pushes toward ELIMINATED. */
    localized_negative_signals: z.array(noFence(500)).max(20),
    /** Key B2B directories for this country (incl. the national one). */
    directories: z.array(namedSource).max(15),
    /** The country's canonical buying channels (associations, fairs, chamber/registry, clusters…). */
    channels: z.array(geoChannelSchema).max(25),
    /** Certifications/registrations buyers in this market expect or require. */
    certifications: z.array(z.string().min(1).max(200)).max(10),
    /** Typical buyer titles at target firms in this market (persona seed). */
    buyer_titles: z.array(z.string().min(1).max(120)).max(10),
    /** One tight paragraph on how the buying channel is structured in this country. */
    market_notes: z.string().min(1).max(4000),
    /** Rough count of firms matching the ICP in this geo cell (the E estimate). */
    estimate: z.number().int().min(0).max(1_000_000).nullable(),
    /** Confidence in the estimate, 0..1. */
    confidence: z.number().min(0).max(1).nullable(),
    /** How the estimate was derived — persisted as the cell's rationale. */
    estimate_basis: z.string().max(1000),
});

export type GeoSpec = z.infer<typeof geoAnalysisSchema>;
export type GeoChannel = z.infer<typeof geoChannelSchema>;
